
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FacilityDocu.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Action
{

    public Action()
    {

        this.ActionAttachments = new HashSet<ActionAttachment>();

        this.ProjectDetails = new HashSet<ProjectDetail>();

        this.StepActions = new HashSet<StepAction>();

    }


    public int ActionID { get; set; }

    public string ActionName { get; set; }

    public string Description { get; set; }



    public virtual ICollection<ActionAttachment> ActionAttachments { get; set; }

    public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }

    public virtual ICollection<StepAction> StepActions { get; set; }

}

}
