
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FacilityDocu.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ModuleStep
{

    public int ID { get; set; }

    public Nullable<int> StepID { get; set; }

    public Nullable<int> ModuleID { get; set; }



    public virtual Module Module { get; set; }

    public virtual Step Step { get; set; }

}

}
