
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FacilityDocu.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectActionTool
{

    public int ProjectActionToolID { get; set; }

    public Nullable<int> ProjectDetailID { get; set; }

    public Nullable<int> ToolID { get; set; }



    public virtual ProjectDetail ProjectDetail { get; set; }

    public virtual Tool Tool { get; set; }

}

}
