
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FacilityDocu.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    public Project()
    {

        this.ProjectDetails = new HashSet<ProjectDetail>();

    }


    public int ProjectID { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public Nullable<System.DateTime> LastUpdatedAt { get; set; }

    public bool Template { get; set; }

    public Nullable<bool> Close { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }

}

}
