
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FacilityDocu.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectDetail
{

    public ProjectDetail()
    {

        this.ProjectActionImages = new HashSet<ProjectActionImage>();

        this.ProjectActionResources = new HashSet<ProjectActionResource>();

        this.ProjectActionTools = new HashSet<ProjectActionTool>();

    }


    public int ProjectDetailID { get; set; }

    public Nullable<int> ProjectID { get; set; }

    public Nullable<int> RigTypeID { get; set; }

    public Nullable<int> ModuleID { get; set; }

    public Nullable<int> StepID { get; set; }

    public Nullable<int> ActionID { get; set; }

    public string Risks { get; set; }

    public string Dimensions { get; set; }

    public string LiftingGears { get; set; }



    public virtual Action Action { get; set; }

    public virtual Module Module { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<ProjectActionImage> ProjectActionImages { get; set; }

    public virtual ICollection<ProjectActionResource> ProjectActionResources { get; set; }

    public virtual ICollection<ProjectActionTool> ProjectActionTools { get; set; }

    public virtual RigType RigType { get; set; }

    public virtual Step Step { get; set; }

}

}
