//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilityDocu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.ProjectActionResources = new HashSet<ProjectActionResource>();
        }
    
        public int ResourceID { get; set; }
        public string ResourceName { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<ProjectActionResource> ProjectActionResources { get; set; }
    }
}
