//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilityDocu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAnalysi
    {
        public int RiskAnalysisID { get; set; }
        public string Activity { get; set; }
        public string Danger { get; set; }
        public string Controls { get; set; }
        public Nullable<int> ProjectDetailID { get; set; }
        public string L { get; set; }
        public Nullable<int> S { get; set; }
        public string Responsible { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
}
