
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FacilityDocu.Data
{

using System;
    using System.Collections.Generic;
    
public partial class RiskAnalysi
{

    public int RiskAnalysisID { get; set; }

    public string Activity { get; set; }

    public string Danger { get; set; }

    public Nullable<decimal> K { get; set; }

    public Nullable<decimal> B { get; set; }

    public Nullable<decimal> E { get; set; }

    public Nullable<decimal> Risk { get; set; }

    public string Controls { get; set; }

    public string K_ { get; set; }

    public string B_ { get; set; }

    public string E_ { get; set; }

    public string Risk_ { get; set; }

    public Nullable<int> ProjectDetailID { get; set; }



    public virtual ProjectDetail ProjectDetail { get; set; }

}

}
