//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilityDocu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public Tool()
        {
            this.ProjectActionTools = new HashSet<ProjectActionTool>();
        }
    
        public int ToolID { get; set; }
        public string ToolName { get; set; }
    
        public virtual ICollection<ProjectActionTool> ProjectActionTools { get; set; }
    }
}
