
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FacilityDocu.Data
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.Projects = new HashSet<Project>();

        this.Projects1 = new HashSet<Project>();

    }


    public string UserName { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }



    public virtual ICollection<Project> Projects { get; set; }

    public virtual ICollection<Project> Projects1 { get; set; }

}

}
